version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3390:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true

volumes:
  db_data:
